---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a Cloud9 IDE for deploying sample applications from AWS DevOps Simplified Book
Parameters:
  AWSDevOpsSimplifiedCloud9InstanceType:
    Description: Cloud9 instance type
    Type: String
    Default: t3.medium
  RepositoryOwner: 
    Type: String
    Description: The owner of the GitHub repository to be used to bootstrap Cloud9
    Default: "akskap"
    AllowedValues: 
      - "akskap"   
  RepositoryName: 
    Type: String
    Description: The name of the GitHub repository to be used to bootstrap Cloud9
    Default: "AWS-DevOps-Simplified"
    AllowedValues: 
      - "AWS-DevOps-Simplified"    
  RepositoryRef: 
    Type: String
    Description: The Git reference to be used to bootstrap Cloud9
    Default: "main"
    AllowedValues: 
      - "main"
Resources:
  AWSDevOpsSimplifiedCloud9LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName:
          Fn::Join:
          - ''
          - - AWSDevOpsSimplifiedCloud9LambdaPolicy-
            - Ref: AWS::Region
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - cloudformation:DescribeStacks
            - cloudformation:DescribeStackEvents
            - cloudformation:DescribeStackResource
            - cloudformation:DescribeStackResources
            - ec2:DescribeInstances
            - ec2:AssociateIamInstanceProfile
            - ec2:ModifyInstanceAttribute
            - ec2:ReplaceIamInstanceProfileAssociation
            - ec2:DescribeIamInstanceProfileAssociations
            - ec2:DescribeVolumes
            - ec2:ModifyVolume
            - iam:ListInstanceProfiles
            - iam:PassRole
            - ssm:DescribeInstanceInformation
            - ssm:SendCommand
            - ssm:GetCommandInvocation
            Resource: "*"
  AWSDevOpsSimplifiedCloud9BootstrapInstanceLambda:
    Type: Custom::AWSDevOpsSimplifiedCloud9BootstrapInstanceLambda
    DependsOn:
    - AWSDevOpsSimplifiedCloud9LambdaExecutionRole
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - AWSDevOpsSimplifiedCloud9BootstrapInstanceLambdaFunction
        - Arn
      REGION:
        Ref: AWS::Region
      Cloud9Name: !GetAtt AWSDevOpsSimplifiedCloud9Instance.Name
      EnvironmentId:
        Ref: AWSDevOpsSimplifiedCloud9Instance
      AWSDevOpsSimplifiedIdeInstanceProfileName:
        Ref: AWSDevOpsSimplifiedCloud9InstanceProfile
      AWSDevOpsSimplifiedIdeInstanceProfileArn:
        Fn::GetAtt:
        - AWSDevOpsSimplifiedCloud9InstanceProfile
        - Arn
      SsmDocument:
        Ref: AWSDevOpsSimplifiedCloud9SSMDocument

  AWSDevOpsSimplifiedCloud9BootstrapInstanceLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role:
        Fn::GetAtt:
        - AWSDevOpsSimplifiedCloud9LambdaExecutionRole
        - Arn
      Runtime: python3.9
      MemorySize: 256
      Timeout: '600'
      Code:
        ZipFile: |
          from __future__ import print_function
          import boto3
          import json
          import os
          import time
          import traceback
          import cfnresponse
          
          def lambda_handler(event, context):
              print(event.values())
              # logger.info('context: {}'.format(context))
              responseData = {}

              status = cfnresponse.SUCCESS
              
              if event['RequestType'] == 'Delete':
                  responseData = {'Success': 'Custom Resource removed'}
                  cfnresponse.send(event, context, status, responseData, 'CustomResourcePhysicalID')              
              else:
                  try:
                      # AWS clients
                      ec2 = boto3.client('ec2')
                      ssm = boto3.client('ssm')
          
                      # Get the InstanceId of the Cloud9 IDE
                      instance = ec2.describe_instances(Filters=[{'Name': 'tag:Name','Values': ['aws-cloud9-'+event['ResourceProperties']['Cloud9Name']+'-'+event['ResourceProperties']['EnvironmentId']]}])['Reservations'][0]['Instances'][0]
                      # logger.info('instance: {}'.format(instance))
                      instance_id = instance['InstanceId']
          
                      # Create the IamInstanceProfile request object
                      iam_instance_profile = {
                          'Arn': event['ResourceProperties']['AWSDevOpsSimplifiedIdeInstanceProfileArn'],
                          'Name': event['ResourceProperties']['AWSDevOpsSimplifiedIdeInstanceProfileName']
                      }
                      # logger.info('iam_instance_profile: {}'.format(iam_instance_profile))

                      time.sleep(10)
          
                      # Wait for Instance to become ready before adding Role
                      instance_state = instance['State']['Name']
                      # logger.info('instance_state: {}'.format(instance_state))
                      while instance_state != 'running':
                          time.sleep(5)
                          instance_state = ec2.describe_instances(InstanceIds=[instance_id])
                          # logger.info('instance_state: {}'.format(instance_state))

                      associations = ec2.describe_iam_instance_profile_associations(
                          Filters=[
                              {
                                  'Name': 'instance-id',
                                  'Values': [instance_id],
                              },
                          ],
                      )

                      if len(associations['IamInstanceProfileAssociations']) > 0:
                        for association in associations['IamInstanceProfileAssociations']:
                          if association['State'] == 'associated':
                            print("{} is active with state {}".format(association['AssociationId'], association['State']))
                            ec2.replace_iam_instance_profile_association(AssociationId=association['AssociationId'], IamInstanceProfile=iam_instance_profile)
                      else:
                        ec2.associate_iam_instance_profile(IamInstanceProfile=iam_instance_profile, InstanceId=instance_id)

                      for i in range(1, 30):
                        response = ssm.describe_instance_information(Filters=[{'Key': 'InstanceIds', 'Values': [instance_id]}])
                        if len(response["InstanceInformationList"]) > 0 and \
                              response["InstanceInformationList"][0]["PingStatus"] == "Online" and \
                              response["InstanceInformationList"][0]["InstanceId"] == instance_id:
                          break
                        time.sleep(10)

                      ssm_document = event['ResourceProperties']['SsmDocument']

                      response = ssm.send_command(
                        InstanceIds=[instance_id],
                        DocumentName=ssm_document)

                      command_id = response['Command']['CommandId']

                      waiter = ssm.get_waiter('command_executed')

                      waiter.wait(
                        CommandId=command_id,
                        InstanceId=instance_id,
                        WaiterConfig={
                          'Delay': 10,
                          'MaxAttempts': 30
                        }
                      )
  
                      responseData = {'Success': 'Started bootstrapping for instance: '+instance_id}
                      cfnresponse.send(event, context, status, responseData, 'CustomResourcePhysicalID')
                      
                  except Exception as e:
                      status = cfnresponse.FAILED
                      print(traceback.format_exc())
                      responseData = {'Error': traceback.format_exc(e)}
                  finally:
                      cfnresponse.send(event, context, status, responseData, 'CustomResourcePhysicalID')

  AWSDevOpsSimplifiedCloud9SSMDocument: 
    Type: AWS::SSM::Document
    Properties: 
      DocumentType: Command
      DocumentFormat: YAML
      Content: 
        schemaVersion: '2.2'
        description: Bootstrap Cloud9 Instance
        mainSteps:
        - action: aws:runShellScript
          name: AWSDevOpsSimplifiedCloud9bootstrap
          inputs:
            runCommand:
            - !Sub |
                set -e

                export AWS_REGION="${AWS::Region}"
                export REPOSITORY_OWNER="${RepositoryOwner}"
                export REPOSITORY_NAME="${RepositoryName}"
                export REPOSITORY_REF="${RepositoryRef}"
                export CLOUD9_ENVIRONMENT_ID="${AWSDevOpsSimplifiedCloud9Instance}"

                sudo -E -H -u ec2-user bash -c "curl -fsSL https://raw.githubusercontent.com/${RepositoryOwner}/${RepositoryName}/${RepositoryRef}/toolbox/installer.sh | bash"

  AWSDevOpsSimplifiedCloud9Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
            - ssm.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: "/"

  AWSDevOpsSimplifiedCloud9InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: AWSDevOpsSimplifiedCloud9Role

  AWSDevOpsSimplifiedCloud9Instance:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Description: AWS Cloud9 instance for deploying sample applications from AWS DevOps Simplified Book
      ImageId: amazonlinux-2-x86_64
      AutomaticStopTimeMinutes: 1800
      InstanceType:
        Ref: AWSDevOpsSimplifiedCloud9InstanceType
      Name: "AWS-DevOps-Simplified"
      Tags: 
        - Key: AWS-DevOps-Simplified
          Value: Active

Outputs:
  Cloud9RoleArn:
    Description: The ARN of the IAM role assigned to the Cloud9 instance
    Value: !GetAtt AWSDevOpsSimplifiedCloud9Role.Arn
    
  Cloud9InstanceName:
    Description: Name of the Cloud9 EC2 instance
    Value: !Sub '${AWSDevOpsSimplifiedCloud9Instance.Name}-${AWSDevOpsSimplifiedCloud9Instance}'

  EnvironmentUrl:
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloud9/ide/${AWSDevOpsSimplifiedCloud9Instance}?region=${AWS::Region}'
