version: 0.0
os: linux
files:
  - source: src/web_server.py
    destination: /opt/ads-server/
hooks:
  BeforeInstall:
    - location: src/deployment_scripts/stop_server.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: src/deployment_scripts/install_dependencies.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: src/deployment_scripts/start_server.sh
      timeout: 30
      runas: root



